### ISSUE TITLE
ThreadError Attempt to unlock a mutex which is not locked lib/vertica/connection.rb:298:in `unlock'

### ISSUE THREAD

**Issue by sonots** [wvanbergen/vertica#68]
```
ThreadError Attempt to unlock a mutex which is not locked lib/vertica/connection.rb:298:in `unlock'
lib/vertica/connection.rb:298:in `process_message'
lib/vertica/connection.rb:398:in `startup_connection'
lib/vertica/connection.rb:446:in `boot_connection'
lib/vertica/connection.rb:329:in `run_in_mutex'
lib/vertica/connection.rb:146:in `query'
```

https://github.com/wvanbergen/vertica/blob/200d317e64130ce333c7c44c6362618858ccd3cc/lib/vertica/connection.rb#L298

`@mutex.unlock if @mutex.locked?` correctly or this line is not needed?

**Comment by wvanbergen** [comment]
This for sure is a bug, but adding `if @mutex.locked?` will solve the symptom, but not the cause. 

A connection can only every be processing one query, so once we get `ReadyForQuery` the mutex should always be locked.
